### ISSUE TITLE
The initial click in the edit fields are not indented.

### ISSUE THREAD

**Issue by jrupesh** [gjroelofs/redmine_codemirror#1]
After installation of the plugin,
Edit a Issue or a News, Click the edit field.
The cursor is not indented. The line number is over written on the text.

![image](https://cloud.githubusercontent.com/assets/4559477/7537796/f9bfcb9a-f5b8-11e4-967b-5657b412d8bd.png)

**Comment by gjroelofs** [comment]
Thanks for the bug report, which version of redmine are you running?

**Comment by gjroelofs** [comment]
Confirmed for 2.3.x.
