### ISSUE TITLE
CodeMirror is what/where?

### ISSUE THREAD

**Issue by DarkSideGeek** [gjroelofs/redmine_codemirror#2]
Pardon the ignorance, but "CodeMirror integration" means what exactly? Does one need something called 'CodeMirror' installed that this plugin talks to?

I had installed on 2.3.1 and didn't see a difference in the editor view. Now I am revisiting, having upgraded to 2.6.9, and still I don't see anything out of the ordinary. 

I have the CKeditor plugin installed, along with per_project_formatting, so a project has a choice of "ckeditor", "textile", or "markdown". The Textile editor view is as before, w/o the WYSIWYM. No Javascript console errors or in production.log that I can see.

**Comment by gjroelofs** [comment]
CodeMirror is a replacement editor and should replace the default editor that Redmine uses.
While editing you should be able to see the view displayed by the screenshot provided in the repo.

I will look into whether the CKEditor plugin causes issues with regards to the hooks.
If possible could you check whether removing the CKEditor plugin and switching to the Textile Editor enables the editor?
